<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Deterministic>true</Deterministic>
    <Version>0.1.0</Version>
    <InformationalVersion>0.1.0-primer5-style-preview</InformationalVersion>
  </PropertyGroup>
</Project>
